<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$hasDerivative = $plugins->get('hasDerivative');

$derivatives = $hasDerivative($resource);

$resourceId = $resource->id();

$labels = [
    'zip' => 'Zip of all files', // @translate
    'zipm' => 'Zip of media files', // @translate
    'zipo' => 'Zip of other files', // @translate
    'pdf' => 'Pdf', // @translate
    'txt' => 'Text', // @translate
    'text' => 'Extracted text', // @translate
    'alto' => 'Ocr Xml Alto', // @translate
    'iiif-2' => 'Iiif manifest v2', // @translate
    'iiif-3' => 'Iiif manifest v3', // @translate
    'pdf2xml' => 'Text from pdf as xml', // @translate
];
?>

<?php if ($derivatives): ?>

<div class="derivative-medias">
    <aside class="derivative-list" data-text-warn="<?= $translate('Are you sure to download this file?') ?>" data-text-warn-size="<?= $translate('Are you sure to download the file of {size}?') ?>" data-text-no="<?= $translate('No') ?>" data-text-yes="<?= $translate('Yes') ?>" data-text-ok="<?= $translate('Ok') ?>" data-text-queued="<?= $translate('The file is in queue. Reload the page later.') ?>" data-text-units="<?= $escapeAttr($translate('["Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"]')) ?>">
        <ul>
            <?php foreach ($derivatives as $type => $derivative): ?>
            <?php if (!empty($derivative['feasible'])): ?>
            <li class="export-<?= $type ?>">
                <a href="#" data-url="<?= $derivative['url'] ?>" data-size="<?= $derivative['size'] ?>" class="derivative-media<?= $derivative['ready'] || $derivative['mode'] === 'live' ? '' : ' on-demand' ?>" download="<?= $resourceId . '.' . $derivative['extension'] ?>">
                    <?= $translate($labels[$type]) ?>
                </a>
            </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </aside>
</div>

<?php endif; ?>
